# Generated by Django 2.2.6 on 2019-11-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('userpw', models.CharField(max_length=20)),
                ('phone_num', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('addr', models.TextField()),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
    ]
