# Generated by Django 2.2.6 on 2019-11-10 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0002_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardData',
            fields=[
                ('board_number', models.AutoField(primary_key=True, serialize=False)),
                ('board_title', models.CharField(max_length=126)),
                ('board_content', models.TextField()),
                ('board_date', models.CharField(max_length=140)),
                ('board_writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.User')),
            ],
        ),
    ]
